server:
  port: 10003
  context-path: /appraise-service
  session:
    timeout: 36000
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 100
  connection-timeout: 20000

## spirng boot 相关配置
spring:
  application:
  name: dubbo-user-provider # 服务提供者名字
  datasource:
    #   数据源基本配置
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ceshi?useUnicode=true&amp;characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

# dubbo 相关配置， 服务注册
dubbo:
  application:
    name: dubbo-user-service-provider
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 10001

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # 别名配置
  type-aliases-package: cn.jsxwsl.dubbo.bean

#显示sql语句
logging:
  level:
    cn.jsxwsl.dubbo.bean: debug

