myProps: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: Solin
      value: SolinValue
    - name: Tom
      value: TomValue
  listProp2:
    - config1Value1
    - config2Value2
  mapProps:
    key1: value1
    key2: value2
#active 与profiles前面要有空格
spring:
  profiles:
   active: dev

