
server:
  port: 80
  
dubbo:
  application:
    name: appraise-web-consumer
  registry:
    address: 192.168.55.13:2181
    protocol: zookeeper
spring:
  application:
    name: appraise-web
 

